### ISSUE TITLE
No license in repo

### ISSUE THREAD

**Issue by jchesterpivotal** [roymarantz/junos-pulse#1]
We'd like to adapt and incorporate these scripts into a project. There's no license file in this repo, so the legal situation falls back to Github's [fairly narrow ToS defaults](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership). We currently have permission to view and fork, but no other copyright license is granted.

Would you be able to apply MIT or BSD license?

**Comment by roymarantz** [comment]
I added a Apache License, Version 2.0.  Have fun.

**Comment by jchesterpivotal** [comment]
Awesome -- thanks!

**Comment by jchesterpivotal** [comment]
Though we note that you have it as "Copyright 2013 Gabe Conradi" :)

**Comment by roymarantz** [comment]
woops, cut and past error.
thanks
